language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.5"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

services:
  - mysql

matrix:
  # Just run the highest and lowest for each branch
  include:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.2.0
  - nvm use 14.2.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
